name: "nuget"

on:
  push:
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
    - "[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

    - name: "Clone repository"
      uses: actions/checkout@v2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: "Publish NuGet"
      run: 'dotnet test --configuration "Release" && dotnet pack --no-build --output "./bin/NuGet" && dotnet nuget push "./bin/NuGet/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.GH_NUGET_KEY_OBGANISM }}"'
