name: "Tests"

on:
  push:
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

    - name: "Clone repository"
      uses: actions/checkout@v2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: "Run tests"
      run: 'dotnet test'
      
    - name: "Publish nuget"
      run: 'dotnet pack --output "./bin/Nuget" --include-symbols --include-source --configuration "Release" && dotnet nuget push "./bin/Nuget/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.GH_NUGET_KEY_OBGANISM }}"'
