name: "tests"

on:
  push:
    branches: [ "master" ]
    tags-ignore: [ "[0-9]+.[0-9]+.[0-9]+" ] # Tests are run before nugetting anyway...

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:

    - name: "Clone repository"
      uses: actions/checkout@v2

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: "Run tests"
      run: 'dotnet test'
